version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_soporte
    environment:
      POSTGRES_DB: microservicio_soporte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN
    restart: always

  soporte-app:
    build: .
    container_name: soporte_app
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microservicio_soporte
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ADMIN
    restart: always

